# Generated by Django 3.2.11 on 2022-01-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categoryweight'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.categoryweight'),
        ),
    ]
